// Problem 2
// =========
// 
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 
//                   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// Find the sum of all the even-valued terms in the sequence which do not
// exceed four million.

function Fibonacci (limit) {
	var list = [1, 2];
	while ((list[list.length -1] + list[list.length -2]) < limit) {

		list.push(list[list.length -1] + list[list.length -2]);
	}
	var evens = list.filter(function(value) {
		return value % 2 === 0
	});
	var total = evens.reduce(function(a, b) {
	  return a + b;
	});
	return total;
}

// TODO: return your answer for this prompt.
// return Fibonacci(100);
return Fibonacci(4000000);
